# Generated by Django 5.2.4 on 2025-08-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftasset',
            name='ipfs_cid',
        ),
        migrations.RemoveField(
            model_name='nftasset',
            name='metadata_url',
        ),
        migrations.RemoveField(
            model_name='nftasset',
            name='minted',
        ),
        migrations.AddField(
            model_name='nftasset',
            name='cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nftasset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nftasset',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
