name: Mint NFT

on:
  push:
    branches:
      - main

jobs:
  mint_nft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NFT minting script
        run: |
          python backend/apps/nft_upload/mint_nft.py
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          INFURA_SECRET: ${{ secrets.INFURA_SECRET }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}